title: Avoimen lähdekoodin yhteistyöverkosto
description: Verkoston tavoitteena on pyrkiä edistämään avoimeen lähdekoodiin perustuvien ratkaisujen hyödyntämistä Suomessa julkisella sektorilla.
show_downloads: false
google_analytics:
theme: jekyll-theme-slate
